apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result-ui
  template:
    metadata:
      labels:
        app: result-ui
    spec:
      containers:
      - name: result-ui
        image: lestof/result-ui
        ports:
          - containerPort: 80